name: one_components
description: A new Flutter package project.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 0.0.1

environment:
  sdk: '>=2.18.0 <3.0.0'
  flutter: ">=3.3.8"

dependencies:
  animated_size_and_fade: ^3.0.0
  another_flushbar: ^1.10.29
  auto_size_text: ^3.0.0
  auto_size_text_field:
    git:
      url: https://github.com/stepushchik-denis-gismart/auto_size_text_field.git
      ref: c428f7ffefa8a385e2109e0997f4c9f5397262a5
  diacritic: ^0.1.3
  dotted_border: ^2.0.0+1
  equatable: ^2.0.3
  flutter:
    sdk: flutter
  flutter_html: ^3.0.0-alpha.5
  flutter_keyboard_visibility: ^5.3.0
  fluttertoast: ^8.0.9
  focus_detector: ^2.0.1
  freezed_annotation: ^2.1.0
  get: ^4.6.5
  image_picker: ^0.8.5+3
  intl: ^0.17.0
  json_annotation: ^4.6.0
  keyboard_actions: ^4.0.1
  linked_scroll_controller: ^0.2.0
  lottie: ^2.1.0
  marquee: ^2.2.3
  one_assets:
    path: ../one_assets
  # qr_code_scanner:
  #   git:
  #     url: https://github.com/xeinebiu/qr_code_scanner.git
  #     ref: fix_break_changes_platform
  rxdart: ^0.26.0
  shimmer: ^2.0.0
  tuple: ^2.0.0

dev_dependencies:
  build_runner: ^2.2.0
  flutter_test:
    sdk: flutter
  freezed: ^2.3.0
  json_serializable: ^6.5.4
